spring:
  application:
    name:  zhang-ai-zero-code
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'AI-zero-code'
      packages-to-scan: com.unique.zhangaizerocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

