# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-3434e12651d94bc7ad629d0e0fc6348b
      model-name: deepseek-v4-pro
      log-requests: true
      log-responses: true
      max-tokens: 8192
      response-format: json-object
      #注意 流式输出不支持 response-format: json-object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-3434e12651d94bc7ad629d0e0fc6348b
      model-name: deepseek-v4-pro
      max-tokens: 8192
      log-requests: true
      log-responses: true

